# Generated by Django 5.2.9 on 2026-02-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flightname", models.CharField(max_length=100)),
                ("flightId", models.CharField(max_length=100)),
                ("start_point", models.CharField(max_length=100)),
                ("endpoint", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("flight_type", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("food_supply", models.CharField(max_length=50)),
            ],
        ),
    ]
